(part "SI1016CX-T1-GE3"
    (packageRef "SOTFL50P160X60-6N")
    (interface
        (port "1" (symbPinId 1) (portName "S1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "G1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "G2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SI1016CX-T1-GE3")
    (property "Mouser_Part_Number" "78-SI1016CX-T1-GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SI1016CX-T1-GE3?qs=ROh%252BA47s9d23BjzCxwa0qg%3D%3D")
    (property "Arrow_Part_Number" "SI1016CX-T1-GE3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/si1016cx-t1-ge3/vishay?region=nac")
    (property "Description" "Mosfet Array 20V 220mW Surface Mount SC-89 (SOT-563F)")
    (property "Datasheet_Link" "https://www.vishay.com/docs/67535/si1016cx.pdf")
    (property "symbolName1" "SI1016CX-T1-GE3")
)
