(part "MF-MSMF200-2"
    (packageRef "FUSC4632X85N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "element14_Part_Number" "")
    (property "element14_Price/Stock" "")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "MF-MSMF200-2")
    (property "Description" "Fuse, PTC, Resettable, SMD, 1812, 2.0A Bourns 2A Surface Mount Resettable Fuse, 8 V")
    (property "Datasheet_Link" "")
    (property "symbolName1" "MF-MSMF200-2")
)
