(part "USB2513B_M2"
    (packageRef "QFN50P600X600X100-37N-D")
    (interface
        (port "1" (symbPinId 1) (portName "USBDM_DN1/PRT_DIS_M1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "USBDP_DN1/PRT_DIS_P1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "USBDM_DN2/PRT_DIS_M2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "USBDP_DN2/PRT_DIS_P2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDDA33_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "USBDM_DN3/PRT_DIS_M3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "USBDP_DN3/PRT_DIS_P3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VDDA33_2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "TEST") (portType INOUT))
        (port "12" (symbPinId 12) (portName "PRTPWR1/BC_EN1") (portType INOUT))
        (port "13" (symbPinId 13) (portName "OCS_N1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "CRFILT") (portType INOUT))
        (port "15" (symbPinId 15) (portName "VDD33_1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "PRTPWR2/BC_EN2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "OCS_N2") (portType INOUT))
        (port "18" (symbPinId 18) (portName "PRTPWR3/BC_EN3") (portType INOUT))
        (port "19" (symbPinId 19) (portName "OCS_N3") (portType INOUT))
        (port "20" (symbPinId 20) (portName "NC_3") (portType INOUT))
        (port "21" (symbPinId 21) (portName "NC_4") (portType INOUT))
        (port "22" (symbPinId 22) (portName "SDA/SMBDATA/NON_REM1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "VDD33_2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "SCL/SMBCLK/CFG_SEL0") (portType INOUT))
        (port "25" (symbPinId 25) (portName "HS_IND/CFG_SEL1") (portType INOUT))
        (port "26" (symbPinId 26) (portName "RESET_N") (portType INOUT))
        (port "27" (symbPinId 27) (portName "VBUS_DET") (portType INOUT))
        (port "28" (symbPinId 28) (portName "SUSP_IND/LOCAL_PWR/NON_REM0") (portType INOUT))
        (port "29" (symbPinId 29) (portName "VDDA33_3") (portType INOUT))
        (port "30" (symbPinId 30) (portName "USBDM_UP") (portType INOUT))
        (port "31" (symbPinId 31) (portName "USBDP_UP") (portType INOUT))
        (port "32" (symbPinId 32) (portName "XTALOUT") (portType INOUT))
        (port "33" (symbPinId 33) (portName "XTALIN/CLKIN") (portType INOUT))
        (port "34" (symbPinId 34) (portName "PLLFILT") (portType INOUT))
        (port "35" (symbPinId 35) (portName "RBIAS") (portType INOUT))
        (port "36" (symbPinId 36) (portName "VDDA33_4") (portType INOUT))
        (port "37" (symbPinId 37) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "USB2513B/M2")
    (property "Mouser_Part_Number" "579-USB2513B/M2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/USB2513B-M2?qs=uus7iwvxYD8fly9xV9Wytg%3D%3D")
    (property "Arrow_Part_Number" "USB2513B/M2")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/usb2513bm2/microchip-technology?utm_currency=USD&region=nac")
    (property "Description" "USB Interface IC 3-Port USB 2.0 Hi-Speed Hub Cont")
    (property "Datasheet_Link" "http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en562310")
    (property "symbolName1" "USB2513B_M2")
)
