(part "DMP3007LSS-13"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "621-DMP3007LSS-13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMP3007LSS-13?qs=qSfuJ%252Bfl%2Fd6BWzce%2FirNpQ%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMP3007LSS-13")
    (property "Description" "MOSFET MOSFET BVDSS: 8V-24V")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/DMP3007LSS.pdf")
    (property "symbolName1" "DMP3007LSS-13")
)
