(part "503398-1892"
    (packageRef "5033981892")
    (interface
        (port "1" (symbPinId 1) (portName "DAT2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CD/DAT3") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CMD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "CLK") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VSS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DAT0") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DAT1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DETECT_LEVER") (portType INOUT))
        (port "10" (symbPinId 10) (portName "DETECT_SWITCH") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "503398-1892")
    (property "Mouser_Part_Number" "538-503398-1892")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/503398-1892?qs=b0v8CoHHvSMxV%252BW12iKaSg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MicroSD SMT Push-Push 1.28mm height MicroSD SMT Push-Push 1.28mm height")
    (property "Datasheet_Link" "http://www.molex.com/webdocs/datasheets/pdf/en-us//5033981892_MEMORY_CARD_SOCKET.pdf")
    (property "symbolName1" "503398-1892")
)
