(part "PESD2CANFD24V-TR"
    (packageRef "SOT95P230X110-3N")
    (interface
        (port "1" (symbPinId 1) (portName "K1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PESD2CANFD24V-TR")
    (property "Mouser_Part_Number" "771-PESD2CANFD24V-TR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PESD2CANFD24V-TR?qs=xZ%2FP%252Ba9zWqbW0qDIUI%252BQ%2FA%3D%3D")
    (property "Arrow_Part_Number" "PESD2CANFD24V-TR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/pesd2canfd24v-tr/nexperia?utm_currency=USD&region=nac")
    (property "Description" "ESD Suppressors / TVS Diodes DIODE ESD PROT")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/PESD2CANFD24V-T.pdf")
    (property "symbolName1" "PESD2CANFD24V-TR")
)
